name: icons_font
version: 1.0.0
description: Icons for Croatiapp
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  change_case: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  icon_font_generator: ^4.1.0
flutter:
  fonts:
    - family: EstrellasIcons
      fonts:
        - asset: lib/font/croatiapp_font.otf
