name: icon_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  change_case: ^2.2.0
  icon_font_generator: ^4.1.0

  # path: ^1.8.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
